<?php

use Drupal\editor\Plugin\InPlaceEditor\Editor;

/**
 * @file
 * Contains paragraphs_starterkit.module
 */

/**
 * Implements hook_preprocess_node() for paragraph node templates.
 *
 * Attach css we need for paragraph types on nodes with paragraphs.
 */
function paragraphs_starterkit_preprocess_node(&$variables) {
  // TODO: Detect existing non empty paragraphs entity reference field.
  $variables['#attached']['library'][] = 'paragraphs_starterkit/drupal.paragraphs_starterkit';
}
