<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\Component\Utility\Html;


/**
 * Implements hook_preprocess_node().
 */
function paragraphs_starterkit_spotlight_preprocess_node(&$variables) {
  $node = $variables['elements']['#node'];
  if ($node->hasField('field_paragraphs')) {
    if (!$node->field_paragraphs->isEmpty() && $bundle = $node->field_paragraphs[0]->entity->bundle()) {
      if ($bundle == 'spotlight') {
        $variables['has_spotlight_title'] = TRUE;
      }
    }
  }
}

/**
 * Implements hook_preprocess_taxonomy_term().
 */
function paragraphs_starterkit_spotlight_preprocess_taxonomy_term(&$variables) {
  $taxonomy_term = $variables['elements']['#taxonomy_term'];
  if ($taxonomy_term->hasField('field_paragraphs')) {
    $paragraphs_field = 'field_paragraphs';
  }
  else if ($taxonomy_term->hasField('field_paragraph')) {
    $paragraphs_field = 'field_paragraph';
  }

  if (!empty($paragraphs_field)) {
    if (!$taxonomy_term->{$paragraphs_field}->isEmpty() && $bundle = $taxonomy_term->{$paragraphs_field}[0]->entity->bundle()) {
      if ($bundle == 'spotlight') {
        $variables['has_spotlight_title'] = TRUE;
      }
    }
  }
}

/**
 * Implements hook_preprocess_paragraphs().
 */
function paragraphs_starterkit_spotlight_preprocess_paragraph(&$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  if ($paragraph->bundle() == 'spotlight') {
    $variables['has_headline'] = (bool) $paragraph->field_has_headline->value;
    $variables['has_socials'] = (bool) $paragraph->field_has_socials->value;
    $variables['text_position'] = $paragraph->field_text_position->value;

    if ($variables['has_socials']) {
      if ($node = \Drupal::routeMatch()->getParameter('node')) {
        _infinite_paragraphs_get_parent_base_data($node, $variables);
      }
      else if ($term = \Drupal::routeMatch()->getParameter('taxonomy_term')) {
        _infinite_paragraphs_get_parent_base_data($term, $variables);
      }
    }

    $anchor_links = [
      '#theme' => 'links',
      '#links' => [],
    ];

    foreach ($paragraph->getParentEntity()->field_paragraphs as $sibling) {
      if ($sibling->entity->id() == $paragraph->id()) {
        continue;
      }
      if (!$sibling->entity->field_anchor->isEmpty()) {
        $anchor_links['#links'][] = [
          'title' => $sibling->entity->field_anchor->value,
          'url' => Url::fromUserInput('#' . Html::getId($sibling->entity->field_anchor->value)),
        ];
      }
    }

    $variables['anchor_links'] = \Drupal::service('renderer')->render($anchor_links);
  }
}
