<?php

/**
 * @file
 * Contains paragraphs_starterkit_image_text.module
 */

use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_preprocess_paragraphs().
 *
 * Attach css we need for paragraph types on nodes with image + text paragraphs.
 */
function paragraphs_starterkit_instagram_preprocess_paragraph(&$variables) {
  /* @var Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->getType() === 'instagram' && !$paragraph->hasField('field_media')) {
    try {
      $instagram_url = $paragraph->field_link->getValue();
      $instagram_url = $instagram_url[0]['uri'];

      $client = \Drupal::httpClient();
      $request = $client->request('GET', 'http://api.instagram.com/oembed?url=' . $instagram_url . '&omitscript=true');

      if ($request->getStatusCode() === 200) {
        $instagram_json = json_decode($request->getBody()->getContents());
        $instagram = array(
          '#markup' => (string) $instagram_json->html,
        );
        $variables['content']['instagram'] = $instagram;
        $variables['#attached']['library'][] = 'paragraphs_starterkit_instagram/instagram.embeds';
      }
    } catch(Exception $e) {}
  }
}
