<?php

/**
 * @file
 * Contains paragraphs_starterkit_images.module
 */

/**
 * Implements hook_preprocess_node() for paragraph node templates.
 *
 * Attach css we need for paragraph types on nodes with images paragraphs.
 */
function paragraphs_starterkit_image_text_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() === 'images') {
    $variables['#attached']['library'][] = 'paragraphs_starterkit_images/drupal.paragraphs_starterkit_images';
  }
}
