<?php

/**
 * @file
 * Contains paragraphs_starterkit_image_text.module
 */

use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_preprocess_paragraphs().
 *
 * Attach css we need for paragraph types on nodes with image + text paragraphs.
 */
function paragraphs_starterkit_twitter_preprocess_paragraph(&$variables) {
  /* @var Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->getType() === 'twitter' && !$paragraph->hasField('field_media')) {
    try {
      $tweet_url = $paragraph->field_link->getValue();
      $tweet_url = $tweet_url[0]['uri'];

      $client = \Drupal::httpClient();
      $request = $client->request('GET', 'https://api.twitter.com/1/statuses/oembed.json?url=' . $tweet_url . '&omit_script=true&lang=de'); // TODO: dynamic language

      if ($request->getStatusCode() === 200) {
        $tweet_json = json_decode($request->getBody()->getContents());
        $tweet = array(
          '#markup' => (string) $tweet_json->html,
        );
        $variables['content']['tweet'] = $tweet;
        $variables['#attached']['library'][] = 'paragraphs_starterkit_twitter/twitter.widgets';
      }
    } catch(Exception $e) {}
  }
}
